/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PoseCorrectorRouteImport } from './routes/pose-corrector'
import { Route as PersonalPlanRouteImport } from './routes/personal-plan'
import { Route as DietPlanRouteImport } from './routes/diet-plan'
import { Route as CalorieCounterRouteImport } from './routes/calorie-counter'
import { Route as IndexRouteImport } from './routes/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PoseCorrectorRoute = PoseCorrectorRouteImport.update({
  id: '/pose-corrector',
  path: '/pose-corrector',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalPlanRoute = PersonalPlanRouteImport.update({
  id: '/personal-plan',
  path: '/personal-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const DietPlanRoute = DietPlanRouteImport.update({
  id: '/diet-plan',
  path: '/diet-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const CalorieCounterRoute = CalorieCounterRouteImport.update({
  id: '/calorie-counter',
  path: '/calorie-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calorie-counter': typeof CalorieCounterRoute
  '/diet-plan': typeof DietPlanRoute
  '/personal-plan': typeof PersonalPlanRoute
  '/pose-corrector': typeof PoseCorrectorRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calorie-counter': typeof CalorieCounterRoute
  '/diet-plan': typeof DietPlanRoute
  '/personal-plan': typeof PersonalPlanRoute
  '/pose-corrector': typeof PoseCorrectorRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calorie-counter': typeof CalorieCounterRoute
  '/diet-plan': typeof DietPlanRoute
  '/personal-plan': typeof PersonalPlanRoute
  '/pose-corrector': typeof PoseCorrectorRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calorie-counter'
    | '/diet-plan'
    | '/personal-plan'
    | '/pose-corrector'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calorie-counter'
    | '/diet-plan'
    | '/personal-plan'
    | '/pose-corrector'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/calorie-counter'
    | '/diet-plan'
    | '/personal-plan'
    | '/pose-corrector'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalorieCounterRoute: typeof CalorieCounterRoute
  DietPlanRoute: typeof DietPlanRoute
  PersonalPlanRoute: typeof PersonalPlanRoute
  PoseCorrectorRoute: typeof PoseCorrectorRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pose-corrector': {
      id: '/pose-corrector'
      path: '/pose-corrector'
      fullPath: '/pose-corrector'
      preLoaderRoute: typeof PoseCorrectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-plan': {
      id: '/personal-plan'
      path: '/personal-plan'
      fullPath: '/personal-plan'
      preLoaderRoute: typeof PersonalPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet-plan': {
      id: '/diet-plan'
      path: '/diet-plan'
      fullPath: '/diet-plan'
      preLoaderRoute: typeof DietPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calorie-counter': {
      id: '/calorie-counter'
      path: '/calorie-counter'
      fullPath: '/calorie-counter'
      preLoaderRoute: typeof CalorieCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalorieCounterRoute: CalorieCounterRoute,
  DietPlanRoute: DietPlanRoute,
  PersonalPlanRoute: PersonalPlanRoute,
  PoseCorrectorRoute: PoseCorrectorRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
